### ISSUE TITLE
Investigate nvm usage

### ISSUE THREAD

**Issue by ddgenome** [atomist-skills/npm-build-skill#73]
There is no need to install multiple version of node using nvm in the Dockerfile. The setting of environment variables and source of the nvm startup script may be able to be streamlined.

**Comment by ddgenome** [comment]
https://github.com/nvm-sh/nvm

**Comment by cdupuis** [comment]
> There is no need to install multiple version of node using nvm in the Dockerfile.

That was added to speed up the startup of the skill. Have some versions ready without a lazy install which takes time.
